#!/usr/bin/env bash
# Builds DistKV on the load generator (same OS and CPU architecture as the
# nodes) and copies the binaries to every instance over the private network.
#
#   deploy/scripts/deploy.sh
set -euo pipefail
# shellcheck source=deploy/scripts/common.sh
source "$(dirname "$0")/common.sh"
require_inventory

LOADGEN=$(public_ip loadgen)

echo "== waiting for instances to finish booting (cloud-init)"
for host in $(all_hosts); do
  ip=$(public_ip "$host")
  for attempt in $(seq 90); do
    if remote "$ip" test -f /var/lib/distkv-ready 2> /dev/null; then break; fi
    if (( attempt == 90 )); then
      echo "$host ($ip) is not ready after 15 minutes; see /var/log/cloud-init-output.log" >&2
      exit 1
    fi
    sleep 10
  done
  echo "   $host ready"
done

echo "== copying sources to the load generator"
rsync -az --delete -e "ssh ${ssh_opts[*]} -i $SSH_KEY" \
  --exclude build/ --exclude .git/ --exclude deploy/.generated/ --exclude 'deploy/terraform/.terraform/' \
  --exclude '*.tfstate*' --exclude bench/results/ \
  "$REPO_DIR/" "ubuntu@$LOADGEN:$REMOTE_DIR/src/"

echo "== building (release) on the load generator"
remote "$LOADGEN" "cd $REMOTE_DIR/src && cmake --preset release -DKV_BUILD_TESTS=OFF > /dev/null \
  && cmake --build --preset release 2>&1 | tail -3 \
  && cp build/release/distkv-server build/release/distkv-coordinator build/release/distkv-admin $REMOTE_DIR/bin/"

echo "== distributing binaries from the load generator"
# The load generator uses the cluster's own key (generated by Terraform) to
# reach the other instances by private IP.
scp "${ssh_opts[@]}" -i "$SSH_KEY" -q "$SSH_KEY" "ubuntu@$LOADGEN:.ssh/cluster_key"
remote "$LOADGEN" chmod 600 .ssh/cluster_key
for host in coordinator $(node_ids); do
  ip=$(private_ip "$host")
  remote "$LOADGEN" "scp -q -o StrictHostKeyChecking=accept-new -i .ssh/cluster_key \
    $REMOTE_DIR/bin/distkv-server $REMOTE_DIR/bin/distkv-coordinator $REMOTE_DIR/bin/distkv-admin \
    ubuntu@$ip:$REMOTE_DIR/bin/"
  echo "   $host ($ip)"
done

echo "Deployed. Next: deploy/scripts/start.sh"
